version: '3.4'

services:

  math-api-flask-prod:
    build:
      context: .
      dockerfile: Dockerfile.flask
      args:
        branch: master
        gitproject: math-api
    ports:
      - 8080:8000
    volumes:
      - /home/david/repos/teaminternational_davidleal/math-api:/app/
    entrypoint: ['uwsgi', '--socket', '0.0.0.0:8000', '--processes', '5', '--protocol=http', '--module', 'app:app']
